Feature/cat 98
Nexters/PomoNyang-iOS pull request #15
Opened 2024-08-03 18:07 UTC by Jihyun247

## [#98] FEAT : API request 및 AuthService 구현

## 관련된 문서 📄

## 무엇에 관한 PR 인가요? 🙋
API request 및 AuthService 구현

## 어떤 것을 작업하셨나요? 🛠
- api request loader를 통해 서버통신
- authService에 토큰 관련 api를 예시로 구현

## 🌱 PR Point
- Sources에 위치한 APIRequestLoader 에 대하여 .... 우선 더 시간들여 수정하기 전에 pr 올리는게 낫겠다 싶어 피알포인트로 남겨욥 ㅜ
- 토큰 인터셉터는 해당 이슈 말고 스플래시 뷰 관련 이슈에서 마무리 지어 합치겟슴다

2024-08-04 08:26 UTC, devMinseok reviewed
추가로 AuthService 모듈 Project.swift파일이 없는데 이것도 확인해줘!
+ make graph로 모듈 그래프 동기화도 해주면 좋을거 같아! (요건 자동화를 해놓던가 해야겠다)

2024-08-04 08:26 UTC, devMinseok commented on Projects/Domain/AuthService/Sources/API/AuthAPIClient.swift
> +}
AuthService 모메인 모듈은 굳이 Dependencies를 써서 의존성 관리를 할필요가 있을까?
개인적으로는 미들웨어로써 함수정도만 정의해서 사용하는게 어떨까 싶어서!
```swift
public func login(
  deviceId: String,
  keychainClient: KeychainClient
) async throws -> AuthDTO.Response.TokenResponseDTO {
  ...
}
```

2024-08-04 08:26 UTC, devMinseok commented on Projects/Shared/Shared/Sources/Exports.swift
> +@_exported import DIContainer
이것도 제거해줘!

2024-08-04 08:29 UTC, devMinseok commented
병합 전에 feature/CAT-98 <- develop 대상으로 rebase후 conflict는 있으면 수정 해줭!

2024-08-04 08:34 UTC, devMinseok commented
APIClient의 Preview폴더는 내가 처음에 만들때 들어간거 같은데 제거하면 좋을거 같아!

2024-08-04 13:47 UTC, Jihyun247 commented on Projects/Domain/AuthService/Sources/API/AuthAPIClient.swift
> +}
흐어 조은 생각이야

2024-08-04 13:52 UTC, Jihyun247 commented
> 병합 전에 feature/CAT-98 <- develop 대상으로 rebase후 conflict는 있으면 수정 해줭!

apiclient preview 삭제 코멘트까지 반영 완료햇슴다,, ~.~ 누락된 것도 다 올렸어욥

2024-08-05 00:11 UTC, devMinseok requested changes

2024-08-05 00:11 UTC, devMinseok commented on Projects/Core/APIClient/Sources/APIReqeustLoader.swift
> +  public var session: URLSession
동시에 여러번의 api호출을 고려했을때 동시 접근을 막을려면 actor를 써야하지 않을까?

2024-08-05 16:13 UTC, devMinseok commented on Projects/Core/APIClient/Sources/APIReqeustLoader.swift
> +  public var session: URLSession
추후 PR에서 개선 필요

2024-08-05 16:13 UTC, devMinseok approved these changes

2024-08-05 16:17 UTC, Jihyun247 commented on Projects/Core/APIClient/Sources/APIReqeustLoader.swift
> +  public var session: URLSession
다음 이슈에서 이어집니다 .., 🥹

2024-08-05 16:17 UTC, merged