[CAT-162] Feature: Splash 구현
Nexters/PomoNyang-iOS pull request #20
Opened 2024-08-08 18:35 UTC by Jihyun247

## [CAT-162] Feature: Splash 구현

## 무엇에 관한 PR 인가요? 🙋
Splash 기능 구현

## 어떤 것을 작업하셨나요? 🛠
1. appCore onAppear 시 splash로 이동
2. splash에서 database initialized 시 다음 이동 뷰 결정 로직 실행
3. 이동 뷰 결정 로직

## 🌱 PR Point
위 3번의 이동 뷰 결정 로직 입니닷

1. 디바이스 아이디가 키체인에 있는지 확인
  1-1 있다면 존재하는 토큰이 키체인에 있는지 확인
    1-1-1 있다면 유저디폴트에서 온보딩 끝냄 여부 확인
      1-1-1-1 끝냈다면 홈뷰로 이동
        1-1-1-2 안끝냈다면 온보딩뷰로 이동
    1-1-2 없다면 login()
  1-2 없다면 디바이스 아이디 발급, 키체인 저장 후 -> login()

디바이스 아이디가 매개변수인 login() 메서드
구현: 발급된 디바이스 아이디로 /tokens 로그인 -> 발급받은 token 키체인 저장 -> 온보딩 뷰로 이동

2024-08-09 15:55 UTC, devMinseok approved these changes
고생했어! 👍👍
사용하지 않는 불필요 모듈은 제거하면 좋을거 같앙

2024-08-09 15:55 UTC, devMinseok commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +    var why: String?
이거 테스트하다가 들어간거 같네 ㅋㅋㅋ

2024-08-09 15:55 UTC, devMinseok commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +      try await Task.sleep(for: .seconds(3))
3초 기다리는건 스플래시화면을 3초동안 보여주려고 넣은건가?

2024-08-09 15:55 UTC, devMinseok commented on Projects/Core/KeychainClient/Interface/Keys.swift
> +}
KeychainClient는 오로지 키체인에 데이터를 저장 또는 로드하기위한 목적을 위해 설계됐다고 생각하면 좋을거 같아.
그래서 어딘가에 종속될만한 코드는 최대한 KeychainClient를 사용하는 도메인에 넣어두면 어떨까?

2024-08-09 15:55 UTC, devMinseok commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +      _ = keychainClient.create(key: KeychainKeys.accessToken.rawValue, data: response.accessToken)
KeychainClient를 직접사용하지 않고 AuthService에서 사용하면 어떨까?
로그인 후 response를 받고 데이터를 저장하는것 까지 도메인에서 처리하는거지

2024-08-09 15:55 UTC, Jihyun247 commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +    var why: String?
아뭐얔ㅋㅋ삭제안했네

2024-08-09 15:56 UTC, Jihyun247 commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +      try await Task.sleep(for: .seconds(3))
엉 디자인팀한테 물어보니 1.5초로 잡을까 하더라구

2024-08-09 16:09 UTC, Jihyun247 commented
> 고생했어! 👍👍 사용하지 않는 불필요 모듈은 제거하면 좋을거 같앙

사용하지 않는 모듈 머가 있지 ?? AppFeature 이거 삭제해도 되는건가 ?

2024-08-09 16:12 UTC, Jihyun247 commented on Projects/Core/KeychainClient/Interface/Keys.swift
> +}
요 키 값들을 한곳에 저장해두고 싶어서 예시로 두어봤는데, 그 키값 각각 사용되는 도메인 모듈에 정의해놓자는 이야기인가 !!

2024-08-09 16:12 UTC, Jihyun247 commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +      _ = keychainClient.create(key: KeychainKeys.accessToken.rawValue, data: response.accessToken)
아하 조은생각이다 !!

2024-08-09 16:16 UTC, Jihyun247 commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +      _ = keychainClient.create(key: KeychainKeys.accessToken.rawValue, data: response.accessToken)
흠 그렇게 되면 authservice의 login()이 apiclient, keychianclient 두개를 모두 받는거구나

2024-08-10 00:33 UTC, devMinseok commented
> 사용하지 않는 모듈 머가 있지 ?? AppFeature 이거 삭제해도 되는건가 ?

Example, Tests, Testing 이런모듈타겟들은 사용안하면 그냥 제거 해줘!

2024-08-10 00:36 UTC, devMinseok commented on Projects/Core/KeychainClient/Interface/Keys.swift
> +}
맞아맞아 최대한 목적에 맞게 역할 분리를 하는거지

2024-08-10 00:40 UTC, devMinseok requested changes

2024-08-10 00:40 UTC, devMinseok commented on Projects/Feature/SplashFeature/Sources/SplashCore.swift
> +  }
이런 코드는 AuthService에서 제공하는게 맞는거 같아

2024-08-10 14:54 UTC, merged

2024-08-10 14:56 UTC, Jihyun247 commented on Projects/Core/KeychainClient/Interface/Keys.swift
> +}
요것은 온보딩 하면서 옮겨놓겟슴다