[CAT-176] Onboarding paging뷰 ui 및 기능구현
Nexters/PomoNyang-iOS pull request #25
Opened 2024-08-13 20:49 UTC by Jihyun247

## [CAT-176] FEAT : Onboarding paging뷰 ui 및 기능구현

## 관련된 문서 📄

## 무엇에 관한 PR 인가요? 🙋
Onboarding paging뷰

## 어떤 것을 작업하셨나요? 🛠
탭바로 구현했습니다
- dragging infinite carousel
- user getsture가 없을 땐 timer를 통한 자동 infinite carousel

## 🌱 PR Point
- ScrollView로 구현하려다가 uiScrollDelegate를 쓰니까 끝도 없어져서 다시 탭바로 넘어왔슴다. RandomAccessCollection의 이점에 대해서는 더 공부해봐야할 것 같아요. 아시는 것 있으면 정보 부탁드림다. 우선은 인덱스를 계속 이리저리 옮겨다녀야해서 써보면 좋을까 싶어서 써봤어요

2024-08-14 11:21 UTC, Jihyun247 commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +import OnboardingFeatureInterface
알려줘서 감사함다 ..!!!!!!!!

2024-08-14 11:22 UTC, Jihyun247 commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingItem.swift
> +    subTitle: "일정 시간 집중과 휴식을 반복해 번아웃을 방지하고\n짧은 시간의 몰입을 경험해보세요.")
아 Image가 Hashable 하지 않아서 방법을 고민하다가 우선 UIImage로 해뒀는데, 어떻게 하는게 조을까 ? ? 온보딩모델구조체 중에 Image 빼고 나머지만 해셔블 하게 두어도 상관 없을까 ? ?

2024-08-14 18:53 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingItem.swift
> +    subTitle: "일정 시간 집중과 휴식을 반복해 번아웃을 방지하고\n짧은 시간의 몰입을 경험해보세요.")
음... 애초에 Hashable을 채택할 필요가 없을거 같은데? Equatable을 채택하면 해결될거 같고, 이미 Identifiable이 채택되어있어서 Onboarding.swift 에서는 ForEach엔 id를 명시적으로 지정할 필요도 없을거 같아.

`ForEach(store.fakedData) { item in ...`

2024-08-14 19:21 UTC, devMinseok requested changes

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingView.swift
> +            ForEach(store.fakedData, id: \.hashValue) { item in
이미 OnboardingItem이 Identifiable을 채택하고 있어서 이건 제거해도 괜찮을거 같아

```suggestion
            ForEach(store.fakedData) { item in
```

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +    var fakedData: RandomAccessEquatableItems<OnboardingItem> = .init(elements: [])
data와 fakedData로 나눈 이유가 있을까?

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +  private enum CancelID { case timer }
CancelID를 해당 Reducer외부에서 사용할게 아니니까 core 함수 내부에 이동시켜서 접근을 제한하는게 좋을거 같아

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +    case _resetTofront
이 case만 앞에 `_`를 붙인 이유가 있을까?

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +    case _resetTofront
만약에 구분할 필요가 있는거라면 아래처럼 하면 좋을거 같아!

```suggestion
    case timer(TimerAction)
    enum TimerAction {
      case start
      case end
      case ticked
    }
```

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +        .debounce(id: "timerStart", for: .seconds(2), scheduler: DispatchQueue.main)
이런식으로 timerDebounce case 추가하고 쓰면 좋을거 같아.
그리고 mainQueue는 Dependencies에서 기본적으로 제공해주는걸 쓰는게 좋을거 같아!
```
@Dependency(\.mainQueue) var mainQueue

private func core(_ state: inout State, _ action: Action) -> EffectOf<Self> {
  enum CancelID { case timer, timerDebounce }
  ...
  .debounce(id: CancelID.timerDebounce, for: .seconds(2), scheduler: self.mainQueue)
  ...
}
```

2024-08-14 19:21 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +      let timerStartAction: Effect<Action> = .send(._timerStart)
이걸 참고해서 아래처럼 수정하는게 좋을거 같아!
https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/performance#Sharing-logic-with-actions

```suggestion
      let timerEndAction: Effect<Action> = .run { send in await send(._timerEnd) }
      let timerStartAction: Effect<Action> = .run { send in await send(._timerStart) }
```

2024-08-15 07:07 UTC, Jihyun247 commented on Projects/Feature/Feature/Sources/AppCore.swift
> +//      return .none
아 ...! 그런 이유에서라면 놓치기 쉬운 부분은 아예 없애는게 좋지 !! 디폴트 없앴습니다!

2024-08-15 07:08 UTC, Jihyun247 commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingItem.swift
> +}
아 피알 포인트에 적어두긴 했는데, 이것저것 시도하다가 인덱스를 왔다갔다 하는데에 randomAccessCollection이 용이하다고 해서 한번 써봤어. 근데 아직 그 이점은 잘 모르겠어서 우선 민석과 얘기해보려고 냅뒀다 ..! 혹시 요거 써본 적 있어 ?

2024-08-15 07:11 UTC, Jihyun247 commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +    case _resetTofront
아 나는 보통 뷰에서 직접 보내는 action이 아닌 '리듀서 안에서만 왔다갔다 하는 internal action'이라고 _를 붙여서 구분해줬었어 !! 타이머끼리 묶은건 아닌데 어떻게 하는게 좋을까 ~?~?

2024-08-15 07:17 UTC, Jihyun247 commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingItem.swift
> +    subTitle: "일정 시간 집중과 휴식을 반복해 번아웃을 방지하고\n짧은 시간의 몰입을 경험해보세요.")
맞네욥, 원래는 ScrollView의 position을 사용하려고 하다보니 Hashable을 채택했었는데, 간과한 부분 감삼다 밑에 fakeddata id를 hashvalue로 한 것도 필요가 없구만

2024-08-15 07:23 UTC, Jihyun247 commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +    var fakedData: RandomAccessEquatableItems<OnboardingItem> = .init(elements: [])
근본?적으론 data가 실제 3개의 데이터고, fakedData는 맨앞에 마지막페이지 하나, 맨뒤에 첫페이지 하나를 붙인거잖아 ?
그래서 원data를 따로 두는게 좋겠다고 생각하기도 했고, (쓰이진 않지만)
그리고 밑에 페이징뷰 (동그라미점 세개) 의 인덱스는 원data의 인덱스를 따라가게 두기 위해서 data/fakedData 두개로 나눴어 !

2024-08-15 07:30 UTC, devMinseok commented on Projects/Feature/OnboardingFeature/Sources/Onboarding/OnboardingCore.swift
> +    case _resetTofront
reducer 내부에서만 쓰일땐 `_` 붙이는거 나쁘지 않은거 같아!

2024-08-15 07:35 UTC, devMinseok submitted a review, later dismissed
고생했어! 👏

2024-08-15 07:38 UTC, merged