[CAT-223] DesignSystem InputField
Nexters/PomoNyang-iOS pull request #31
Opened 2024-08-16 18:53 UTC by Jihyun247

## [CAT-223] DesignSystem InputField

## 무엇에 관한 PR 인가요? 🙋
InputField

## Recorded View
https://github.com/user-attachments/assets/16379b10-d9a6-4515-89b6-a84ba7b2897b

## 어떤 것을 작업하셨나요? 🛠
- InputFieldStyle 구현
- InputField View 구현

## 🌱 PR Point
- 최대한 TextfieldStyle 내부에서 에러까지 하는 방법은 없을지 생각해보았는데, '에러가 딸려있으려면 textfield label 외부에 있어야하니까 View를 하나 만들어야겠다' 라는 생각까지만 도달했슴다 방법을 아신다면 help..
- InputField라는 View를 만들고, InputFieldErrorProtocol을 채택하는 error enum만 받기 위해 제너릭을 썼는데, 이것 또한 더 좋은 방법을 아신다면 help ...
- 민석 슨생님 처럼 깔끔하게 만들기 쉽지 않네요

2024-08-16 21:28 UTC, devMinseok requested changes
고생했어! Placeholder관련해서 어려움이 있는거 같던데 ㅋㅋ 코멘트 참고해줭

2024-08-16 21:28 UTC, devMinseok commented on Projects/Shared/DesignSystem/Sources/Component/InputField/InputField.swift
> +  // MARK: Placeholder Color를 TextFieldStyle 내부에서 변경하는 방법 Plz...
나는 SwiftUI에서 Placeholder를 커스텀 해야할때 이렇게 사용해!

``` swift
extension View {
  public func placeholder<Content: View>(
    when shouldShow: Bool,
    alignment: Alignment = .leading,
    @ViewBuilder placeholder: () -> Content
  ) -> some View {
    ZStack(alignment: alignment) {
      placeholder().opacity(shouldShow ? 1 : 0)
      self
    }
  }
}
```

``` swift
TextField("", text: $store.text.sending(\.textInputted))
  .placeholder(when: store.text.isEmpty) {
    Text("PLACEHOLDER")
      .foregroundColor(.gray50)
      .font(.body)
    }
```

2024-08-17 03:41 UTC, devMinseok commented
TextField의 Style을 더 커스텀 할 수 있는지 확인해봤는데 TextField의 스타일 자체는 viewBuilder로 받지 않다보니까 한계가 있네 ㅠ
지금처럼 InputField View를 만들어서 TextField를 넣는게 제일 이상적인거 같아!

```swift
extension TextField where Label == EmptyView {
  init(
    text: Binding<String>,
    placeholder: String,
    error: InputFieldErrorProtocol
  ) {
    self.init(
      text: text, // 뭔가 해줄 수 있는게 없다...
      prompt: Text(placeholder).foregroundStyle(Color.black),
      label: EmptyView.init
    )
  }
}
```

2024-08-17 05:29 UTC, Jihyun247 commented on Projects/Shared/DesignSystem/Sources/Component/InputField/InputField.swift
> +  // MARK: Placeholder Color를 TextFieldStyle 내부에서 변경하는 방법 Plz...
옹 ..! textFieldStyle 내부에서 placeholder를 건드리는 방법을 암만 찾아도 못보겠더라곱 ...
iOS15부터는 TextField prompt라는 매개변수에 placeholder 커스텀이 가능하긴 하던데 그래서 결국 prompt 써서 했어 ㅋㅅㅋ
`TextField(
        placeholder,
        text: $text,
        prompt: Text(placeholder)
          .foregroundStyle(Alias.Color.Text.disabled)
      )`

2024-08-17 05:32 UTC, merged